name: Install workspaces

inputs:
  type:
    description: 'release type'
    required: true
  access_token:
    description: 'access token'
    required: true

runs:
  using: composite
  steps:
    - uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-release
    - run: 'sudo apt install jq'
      shell: bash

    - run: 'moon run :bump -- ${{ inputs.type }}'
      shell: bash
    - run: "yarn version --no-git-tag-version --${{ inputs.type }}"
      shell: bash
    - run: |
        VERSION=$(jq -r .version package.json)
        echo "Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: bash

    - run: git config --global user.email "ci@ci.com"
      shell: bash
    - run: git config --global user.name "CI"
      shell: bash
    - run: 'git add .'
      shell: bash
    - run: 'git commit -m "release: $VERSION"'
      shell: bash
    #- run: 'git tag $VERSION'
    #  shell: bash
    #- run: 'git push origin $VERSION'
    #  shell: bash
    - run: 'echo https://SimTheFool:${{ inputs.access_token }}@github.com/SimTheFool/ttl_dsl.git'
      shell: bash
    - run: 'https://USERNAME:${GH_TOKEN}@github.com/OWNER/REPO.git'
      shell: bash