name: Install workspaces

inputs:
  type:
    description: 'release type'
    required: true

runs:
  using: composite
  steps:          
    - run: 'cargo install cargo-release'
      shell: bash
    - run: 'sudo apt install jq'
      shell: bash

    - run: 'moon run :bump -- ${{ inputs.type }}'
      shell: bash
    - run: "yarn version --no-git-tag-version --new-version --${{ inputs.type }}"
      shell: bash
    - run: "jq -r .version package.json"
      shell: bash