[package]
name = "lib_ts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = {version = "0.2.11", features = ["js"]}
js-sys = "0.3.66"
lib_interpreter = { path = "../lib_interpreter" }
wasm-bindgen = "0.2.89"


[lints.clippy]
new_without_default = "allow"
