WHITESPACE = _{ (" " | "\t" | "\r" | "\n")+ }

ALPHAFIRST = @{ ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }
ALPHATEXT = @{ ASCII_ALPHANUMERIC* }

variable = @{ ALPHAFIRST }
number = @{ ASCII_DIGIT+ }
string = { "\"" ~ (ALPHATEXT) ~ "\"" }
object = { "{" ~ (declaration)* ~ "}" }

value = { variable | number | object | string }

declaration = { variable ~ ":" ~ value }
integration = { ">>" ~ ("." | "/" | ALPHAFIRST | "_")+ ~ ("with" ~ declaration)* }


file = { SOI ~ value ~ EOI }