name: Install workspaces

inputs:
  cache_key:
    description: 'Cache job key'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          
    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: '. -> .cargo/.target'
        prefix-key: 'ttl_dsl_rust'
        shared-key: 'shared_cache'
        key: '${{ inputs.cache_key }}'

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - uses: moonrepo/setup-toolchain@v0

    - run: 'yarn install'
      shell: bash