name: Install workspaces

inputs:
  cache_key:
    description: 'Cache job key'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: moonrepo/setup-toolchain@v0
    
    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: '. -> .cargo/.target'
        prefix-key: 'ttl_dsl_rust'
        shared-key: 'shared_cache'
        key: '${{ inputs.cache_key }}'

    - run: 'yarn install'
      shell: bash