name: Install workspaces

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - uses: 'moonrepo/setup-toolchain@v0'
    
    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: '. -> .cargo/.target'

    - run: 'yarn install'
      shell: bash