name: Bump packages

inputs:
  type:
    description: 'release type'
    required: true
  token:
    description: 'github token'
    required: true

runs:
  using: composite
  steps:
    - uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-release
    - run: 'sudo apt install jq'
      shell: bash

    - run: 'moon run :bump -- ${{ inputs.type }}'
      shell: bash
    - run: "yarn version --no-git-tag-version --${{ inputs.type }}"
      shell: bash

    - run: |
        VERSION=$(jq -r .version package.json)
        echo "version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV
      shell: bash

    - run: |
          git config --global user.email "ci@ci.com"
          git config --global user.name "CI"
          git config --unset http.https://github.com/.extraheader
          git add .
          git commit -m "release: $VERSION"
          git tag $VERSION
      shell: bash

    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ github.ref }}
        force: true
        tags: true