name: Bump packages

inputs:
  type:
    description: 'release type'
    required: true

outputs:
  version:
    description: "version number"
    value: ${{ steps.versionner.outputs.version }}

runs:
  using: composite
  steps:
    - uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-release
    - run: 'sudo apt install jq'
      shell: bash

    - run: 'moon ci :bump-${{ inputs.type }}'
      shell: bash
    - run: "yarn version --no-git-tag-version --${{ inputs.type }}"
      shell: bash

    - id: versionner
      run: |
        VERSION=$(jq -r .version package.json)
        echo "version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash