name: Test branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      uses: ./.github/actions/install

    - run: 'echo "aaaa"'
    - run: 'moon ci :test'