name: Test branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install
      uses: ./.github/actions/install

    - run: 'moon ci :test'

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install
      uses: ./.github/actions/install

    - run: 'moon ci desk_docviewer:build'

    - uses: actions/upload-artifact@v4
      with:
        path: '.cargo/.target/release/bundle/msi/docviewer_0.1.0_x64_en-US.msi'
        name: 'docviewer'
        retention-days: 15 days