name: Build

on:
  push:
    branches:
      - '**'

jobs:
  #test:
  #  runs-on: ubuntu-latest

  #  steps:
  #  - uses: actions/checkout@v2
  #    with:
  #        fetch-depth: 0

  #  - uses: 'moonrepo/setup-toolchain@v0'
  #  - run: 'yarn install'

  #  - run: 'moon ci :test'

  build_windows:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: '. -> .cargo/.target'

    - name: Sync node version and setup cache
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'yarn'

    - run: 'yarn install'

    - name: Log
      run: ls

    - name: Log 2
      run: cd .. && ls
    
    - uses: tauri-apps/tauri-action@v0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        projectPath: "./desk_docviewer"

    - run: 'ls .cargo/target'