name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo test
      run: |
        echo "something bbbb"
        echo "something elbbbbbse"

    - name: Echo test 2
      run: |
        echo "aaaaa aaiiiiaaa"
        echo "aaaaa iiiiiiiiii"