name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        echo "something bbbb"
        echo "something elbbbbbse"

    - uses: 'moonrepo/setup-toolchain@v0'

    - run: 'moon ci :test'

    - run: |
        echo "aaaaa aaiiiiaaa"
        echo "aaaaa iiiiiiiiii"