name: Test main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install
      uses: ./.github/actions/install

    - run: 'moon ci :test'