name: On push main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'release') }}
    steps:
    - uses: actions/checkout@v4
    - name: Install
      uses: ./.github/actions/install

    - run: 'moon ci :test'

  release:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'release') }}
    needs: test
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install
        uses: ./.github/actions/install

      - run: echo "TYPE=patch" >> $GITHUB_ENV
      - if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
        run: echo "TYPE=minor" >> $GITHUB_ENV
      - if: ${{ startsWith(github.event.head_commit.message, 'fix') }}
        run: echo "TYPE=patch" >> $GITHUB_ENV

      - name: Bump
        id: bump
        uses: ./.github/actions/bump
        with:
          type: $TYPE

      - run: |
          git config --global user.email "ci@ci.com"
          git config --global user.name "CI"
          git config --unset http.https://github.com/.extraheader
          git add .
          git commit -m "release: ${{ steps.bump.outputs.version }}"
          git tag ${{ steps.bump.outputs.version }}
        
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}
          force: true
          tags: true