name: On push main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'release') }}
    steps:
    - uses: actions/checkout@v4
    - name: Install
      uses: ./.github/actions/install

    - run: 'moon ci :test'

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - name: Install
        uses: ./.github/actions/install

      - name: Release minor
        uses: ./.github/actions/release
        if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
        with:
          type: minor
          access_token: ${{secrets.PAT}}

      - name: Release patch
        uses: ./.github/actions/release
        if: ${{ startsWith(github.event.head_commit.message, 'fix') }}
        with:
          type: patch
          access_token: ${{secrets.PAT}}

  build_windows:
    runs-on: windows-latest
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install

      - run: "echo ${{github.ref_name}}"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "./docviewer"

      - uses: actions/upload-artifact@v4
        with:
          path: '.cargo/.target/release/bundle/msi/docviewer_0.1.0_x64_en-US.msi'
          name: 'docviewer'
          retention-days: 15 days