name: On push main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'release') }}
    steps:
    - uses: actions/checkout@v4
    - name: Install
      uses: ./.github/actions/install

    - run: 'moon ci :test'

  release:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'release') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install
        uses: ./.github/actions/install

      - name: Bump minor
        uses: ./.github/actions/bump
        if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
        with:
          type: minor

      - name: Bump patch
        uses: ./.github/actions/bump
        if: ${{ startsWith(github.event.head_commit.message, 'fix') }}
        with:
          type: patch

      - run: git config --global user.email "ci@ci.com"
      - run: git config --global user.name "CI"
      - run: 'git add .'
      - run: 'git commit -m "release: bbbb"'
      - run: 'git tag 0.0.0-alpha.2'
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}
          force: true
          tags: true

  build_windows:
    runs-on: windows-latest
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install

      - run: "echo ${{github.ref_name}}"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "./docviewer"

      - uses: actions/upload-artifact@v4
        with:
          path: '.cargo/.target/release/bundle/msi/docviewer_0.1.0_x64_en-US.msi'
          name: 'docviewer'
          retention-days: 15 days