name: On push main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      uses: ./.github/actions/install

    - run: 'moon ci :test'

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install

      - name: Release minor
        uses: ./.github/actions/release
        if: ${{ ! startsWith(github.event.head_commit.message, 'feat') }}
        with:
          type: minor

      - name: Release patch
        uses: ./.github/actions/release
        if: ${{ ! startsWith(github.event.head_commit.message, 'fix') }}
        with:
          type: patch