name: On push main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'release') }}
    steps:
    - uses: actions/checkout@v4
    - name: Install
      uses: ./.github/actions/install

    - run: 'moon ci :test'

  release:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'release') }}
    needs: test
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install
        uses: ./.github/actions/install

      - name: Bump minor
        uses: ./.github/actions/bump
        if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
        with:
          type: minor
          token: ${{ secrets.PAT }}
      #- if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
      #  run: echo "VERSION=${{ steps.bump-minor.outputs.version }}" >> $GITHUB_ENV

      - name: Bump patch
        uses: ./.github/actions/bump
        if: ${{ startsWith(github.event.head_commit.message, 'fix') }}
        with:
          type: patch
          token: ${{ secrets.PAT }}
      #- if: ${{ startsWith(github.event.head_commit.message, 'fix') }}
      #  run: echo "VERSION=${{ steps.bump-patch.outputs.version }}" >> $GITHUB_ENV

      #- run: |
      #    git config --global user.email "ci@ci.com"
      #    git config --global user.name "CI"
      #    git config --unset http.https://github.com/.extraheader
      #    git add .
      #    git commit -m "release: $VERSION"
      #    git tag $VERSION
      #  
      #- uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.PAT }}
      #    branch: ${{ github.ref }}
      #    force: true
      #    tags: true