name: On release

on:
  push:
    tags:
      - '**'

jobs:  
  build_windows:
    runs-on: windows-latest
    outputs:
      build: ${{ steps.verify.outputs.build }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: tauri-cli
          version: "1.5.9"

      - run: 'moon ci :build --base ${{ github.sha }}^'
 
      - id: verify
        if: hashFiles('.cargo/.target/release/bundle/msi/docviewer_**_x64_en-US.msi.zip') != ''
        run: echo "build=ok" >> $env:GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: hashFiles('.cargo/.target/release/bundle/msi/docviewer_**_x64_en-US.msi.zip') != ''
        with:
          path: '.cargo/.target/release/bundle/msi/**'
          name: 'docviewer_msi'
          if-no-files-found: ignore
          retention-days: 15 days

  release:
    runs-on: ubuntu-latest
    needs: build_windows
    if: ${{ needs.build_windows.outputs.build == 'ok'}}
    steps:

      - uses: actions/download-artifact@v4
        with:
          path: '.cargo/.target/release/bundle/msi'
          name: 'docviewer_msi'

      - run: 'ls ./.cargo/.target/release/bundle/msi'

      - run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq '.packages[] | select(.name == "docviewer") | .version')
          echo "docviewer_version=$VERSION" >> $GITHUB_OUTPUT

      - run: echo "aaaa ${{ env.docviewer_version }}"

      - run: |
          SIG=$(cat .cargo/.target/release/bundle/msi/docviewer_${{ env.docviewer_version }}_x64_en-US.msi.zip)
          echo "docviewer_msi_sig=$VERSION" >> $GITHUB_OUTPUT

      - run: echo "bbbb ${{ env.docviewer_msi_sig }}"

      #- run: moon generate autoupdate ./docviewer/ --defaults -- --version aaa --win_sig ddd

      

      #- uses: softprops/action-gh-release@v1
      #  if: hashFiles('.cargo/.target/release/bundle/msi/docviewer_**_x64_en-US.msi') != ''
      #  with:
      #    files: .cargo/.target/release/bundle/msi/docviewer_**_x64_en-US.msi