name: On release

on:
  push:
    tags:
      - '**'

jobs:
  build_windows:
    runs-on: windows-latest
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: tauri-cli
          version: "1.5.9"

      - run: 'moon ci :build --base ${{ github.sha }}^ '

      #- uses: actions/upload-artifact@v4
      #  with:
      #    path: '.cargo/.target/release/bundle/msi/docviewer_**_x64_en-US.msi'
      #    name: 'docviewer'
      #    if-no-files-found: ignore
      #    retention-days: 15 days

      - uses: softprops/action-gh-release@v1
        with:
          files: .cargo/.target/release/bundle/msi/docviewer_**_x64_en-US.msi