name: On release

on:
  push:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: tauri-cli
          version: "1.5.9"

      - run: 'moon ci :build'

      - uses: actions/upload-artifact@v4
        with:
          path: '.cargo/.target/release/bundle/msi/docviewer_**_x64_en-US.msi'
          name: 'docviewer'
          retention-days: 15 days